"""Data for the Temporal Truth Explorer (design 0003), generated by TypedMem itself.

    python tools/explorer_data.py [out.js]      # default: docs/explorer/data.js

Each scenario is a sequence of real ``AgentMemory.set`` calls in *arrival
order*. After every call the script records what the product then says: the
outcome of the write, the current value (or the conflict), and the full
history. It also records the value in effect in the middle of each month (and at
the as-of date), for the time scrubber.

The page only draws these answers. It never decides what is current itself
(design 0003 §13). ``tests/test_explorer_data.py`` fails if this output and
the committed ``data.js`` disagree.

Everything is evaluated as of a fixed date, so the output is deterministic.
Record ids and write timestamps are left out.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from typedmem import AgentMemory, StateConflict  # noqa: E402

KEY = "account.plan"
AS_OF = datetime(2026, 9, 27, tzinfo=timezone.utc)
# scrubber samples: mid-month (never exactly on a change date), then now
MONTHS = [datetime(2026, m, 15, tzinfo=timezone.utc) for m in range(1, 10)] + [AS_OF]


def day(s: str) -> datetime:
    return datetime.fromisoformat(s).replace(tzinfo=timezone.utc)


# (value, valid_from, source) in the order the records arrive
SCENARIOS = [
    {
        "key": "change",
        "title": "Facts change",
        "question": "What is true now?",
        "writes": [("Free", "2026-01-05", "signup"),
                   ("Pro", "2026-04-01", "billing"),
                   ("Enterprise", "2026-09-01", "billing")],
    },
    {
        "key": "late",
        "title": "Facts arrive late",
        "question": "Does old information overwrite the present?",
        "writes": [("Free", "2026-01-05", "signup"),
                   ("Enterprise", "2026-09-01", "billing"),
                   ("Pro", "2026-04-01", "support ticket")],
    },
    {
        "key": "conflict",
        "title": "Sources disagree",
        "question": "Is there a current truth at all?",
        "writes": [("Free", "2026-01-05", "signup"),
                   ("Enterprise", "2026-09-01", "billing"),
                   ("Pro", "2026-09-01", "crm")],
    },
]


def iso(t: datetime | None) -> str | None:
    return t.date().isoformat() if t else None


def state_at(mem: AgentMemory, t: datetime) -> dict:
    """What ``get`` answers at ``t``: a value, nothing, or a conflict."""
    try:
        return {"current": mem.get(KEY, as_of=t), "conflict": []}
    except StateConflict as c:
        return {"current": None, "conflict": sorted(e.value for e in c.entries)}


def history(mem: AgentMemory) -> list[dict]:
    return [{
        "value": e.value, "status": e.status,
        "valid_from": iso(e.valid_from), "valid_to": iso(e.valid_to),
        "sources": [s.document_id for s in e.sources],
        "conflicts_with": list(e.conflicts_with),
    } for e in mem.history(KEY, as_of=AS_OF)]


def run(scenario: dict) -> dict:
    mem = AgentMemory()                        # in-memory; no API key, no files
    steps = []
    for i, (value, start, source) in enumerate(scenario["writes"], 1):
        r = mem.set(KEY, value, source=source, valid_from=day(start))
        steps.append({
            "arrival": i, "value": value, "valid_from": start, "source": source,
            "outcome": r.outcome,
            **state_at(mem, AS_OF),
            "history": history(mem),
        })
    return {
        "key": scenario["key"], "title": scenario["title"],
        "question": scenario["question"], "state_key": KEY,
        "steps": steps,
        "final": steps[-1],
        "scrub": [{"t": iso(t), **state_at(mem, t)} for t in MONTHS],
    }


def build() -> str:
    # No package version in here: this file is a semantic fixture, and it must
    # only change when TypedMem's answers change, not on every release.
    data = {"source": "TypedMem's own API, via tools/explorer_data.py",
            "as_of": iso(AS_OF), "scenarios": [run(s) for s in SCENARIOS]}
    return ("// generated by tools/explorer_data.py from the real TypedMem API; do not edit\n"
            "window.TRUTH_DATA = " + json.dumps(data, indent=1) + ";\n")


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "explorer" / "data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print("wrote", out)
